Update shadowsocksr

diff --git a/shadowsocksr b/shadowsocksr
--- a/shadowsocksr
+++ b/shadowsocksr
@@ -1,1 +1,76 @@
+#!/bin/bash
+# chkconfig: 2345 90 10
+# description: A proxy, designed to protect your Internet traffic.
 
+# Author: Shiyu <shiyu.weilan@gmail.com>
+
+NAME=ShadowsocksR
+RETVAL=0
+
+check_running(){
+    PID=`ps -ef | grep -v grep | grep -i "server.py m" | awk '{print $2}'`
+    if [ ! -z "$PID" ]; then
+        return 0
+    else
+        return 1
+    fi
+}
+
+do_start(){
+    check_running
+    if [ $? -eq 0 ]; then
+        echo "$NAME (pid $PID) is already running..."
+        exit 0
+    else
+        bash /usr/local/shadowsocksr/run.sh
+        RETVAL=$?
+        if [ $RETVAL -eq 0 ]; then
+            echo "Starting $NAME success"
+        else
+            echo "Starting $NAME failed"
+        fi
+    fi
+}
+
+do_stop(){
+    check_running
+    if [ $? -eq 0 ]; then
+        bash /usr/local/shadowsocksr/stop.sh
+        RETVAL=$?
+        if [ $RETVAL -eq 0 ]; then
+            echo "Stopping $NAME success"
+        else
+            echo "Stopping $NAME failed"
+        fi
+    else
+        echo "$NAME is stopped"
+        RETVAL=1
+    fi
+}
+
+do_status(){
+    check_running
+    if [ $? -eq 0 ]; then
+        echo "$NAME (pid $PID) is running..."
+    else
+        echo "$NAME is stopped"
+        RETVAL=1
+    fi
+}
+
+do_restart(){
+    do_stop
+    do_start
+}
+
+case "$1" in
+    start|stop|restart|status)
+    do_$1
+    ;;
+    *)
+    echo "Usage: $0 { start | stop | restart | status }"
+    RETVAL=1
+    ;;
+esac
+
+exit $RETVAL
